// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using backend_dotnet.Data;

#nullable disable

namespace backend_dotnet.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("backend_dotnet.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "מוצרי חלב"
                        },
                        new
                        {
                            Id = 2,
                            Name = "מאפים"
                        },
                        new
                        {
                            Id = 3,
                            Name = "בשר"
                        },
                        new
                        {
                            Id = 4,
                            Name = "ירקות ופירות"
                        });
                });

            modelBuilder.Entity("backend_dotnet.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            Name = "חלב תנובה"
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            Name = "יוגורט"
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 1,
                            Name = "גבינה צהובה"
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 1,
                            Name = "גבינה לבנה"
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 1,
                            Name = "שוקו"
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 1,
                            Name = "חמאה"
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 2,
                            Name = "לחם קל"
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 2,
                            Name = "לחם שיפון"
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 2,
                            Name = "ביסקוויט"
                        },
                        new
                        {
                            Id = 10,
                            CategoryId = 2,
                            Name = "עוגיות שוקולד"
                        },
                        new
                        {
                            Id = 11,
                            CategoryId = 2,
                            Name = "קרואסאן"
                        },
                        new
                        {
                            Id = 12,
                            CategoryId = 2,
                            Name = "לחם שחור"
                        },
                        new
                        {
                            Id = 13,
                            CategoryId = 3,
                            Name = "חזה עוף"
                        },
                        new
                        {
                            Id = 14,
                            CategoryId = 3,
                            Name = "כבש"
                        },
                        new
                        {
                            Id = 15,
                            CategoryId = 3,
                            Name = "בקר"
                        },
                        new
                        {
                            Id = 16,
                            CategoryId = 3,
                            Name = "בשר רוטב"
                        },
                        new
                        {
                            Id = 17,
                            CategoryId = 3,
                            Name = "קבב"
                        },
                        new
                        {
                            Id = 18,
                            CategoryId = 4,
                            Name = "מלפפון"
                        },
                        new
                        {
                            Id = 19,
                            CategoryId = 4,
                            Name = "עגבנייה"
                        },
                        new
                        {
                            Id = 20,
                            CategoryId = 4,
                            Name = "גזר"
                        },
                        new
                        {
                            Id = 21,
                            CategoryId = 4,
                            Name = "תפוח עץ"
                        },
                        new
                        {
                            Id = 22,
                            CategoryId = 4,
                            Name = "בננה"
                        },
                        new
                        {
                            Id = 23,
                            CategoryId = 4,
                            Name = "תרד"
                        });
                });

            modelBuilder.Entity("backend_dotnet.Models.Product", b =>
                {
                    b.HasOne("backend_dotnet.Models.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("backend_dotnet.Models.Category", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
